feat(#19): 封装请求方法以及添加测试组件
ByteBam/ByteBamFronted pull request #21
Opened 2024-04-18 15:59 UTC by wpfzuishuai

2024-04-18 16:04 UTC, PolarishT requested changes
fix it

2024-04-19 10:11 UTC, Wenrh2004 reviewed
awaiting solution

2024-04-19 10:11 UTC, Wenrh2004 commented on .env.development
> +NEXT_PUBLIC_BASE_URL = /api
这里不用指定host和post嘛，是不是应该指定一下后端的host和post

2024-04-19 10:11 UTC, Wenrh2004 commented on .env.development
> +NEXT_PUBLIC_BASE_URL = /api
这里不用指定host和post嘛，是不是应该指定一下后端的host和post

2024-04-19 10:11 UTC, Wenrh2004 commented on .env.development
> +NEXT_PUBLIC_BASE_URL = /api
这里不用指定host和post嘛，是不是应该指定一下后端的host和post

2024-04-19 17:16 UTC, PolarishT approved these changes
LGTM

2024-04-19 17:23 UTC, Wenrh2004 approved these changes
LGTM

2024-04-19 17:23 UTC, merged